### ISSUE TITLE
Check that lab field "Description" is not in use elsewhere

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#1039]
We are planning to re-purpose the studies_lab field called "description" to use for the custom URLs.  It would be wise to check how that text is currently used, but MKS can't find any evidence. 

- Check whether this variable is displayed on any existing views in the main website/lookit-api. If so, let Melissa know where so we can think about any disadvantages to stealing the field for this purpose.

**Comment by okaycj** [comment]
@mekline 

It's fairly safe to assume that this db value is only used for the lab description on the lab detail page. A non-exhaustive search showed that lab description field is only used in one place the lab detail page.  On this page, it is only used once under the heading of "Lab Description".

**Comment by mekline** [comment]
Great! Closing this
