### ISSUE TITLE
Changing birth year format

### ISSUE THREAD

**Issue by hyesunghwang** [lookit/lookit-api#1096]
**TL;DR**:  Lookit asks for birth date as YYYY-MM-DD, but families typically put it in MM-DD-YYYY format. Can we change it?

**Narrative**
Could we change the birth date entry in new family sign up to MM-DD-YYYY?

**Acceptance Criteria**
Just acknowledgment of the issue and update on when the change is made would be great!

**Implementation Notes**

**Comment by becky-gilbert** [comment]
Thanks @hyesunghwang, this is really useful feedback! 
Just wanted to note that the MM-DD-YYYY format is US-centric. If this is a problem, we could consider something else, like a drop-down menu format, e.g. select the day number, select the month _name_ (to disambiguate from the day), select the year.

**Comment by hyesunghwang** [comment]
Ah that's a good point! Yes, perhaps a drop-down menu specifying these areas would be the best way forward!
