### ISSUE TITLE
Change help text for Lookit authentication via Google Authenticator

### ISSUE THREAD

**Issue by ianchandlercampbell** [lookit/lookit-api#1193]
From Candice: "Small thing, and I'm not sure if this can be easily addressed, but when I tried to log in to Lookit for the second time after I had signed up months previously, the prompt for "enter your one-time password (OTP code)" wasn't clear to me. Is there a way to modify the text on the website to clarify this? Maybe "enter your one-time password (OTP code) sent via Google Authenticator""

**Comment by becky-gilbert** [comment]
@mekline are you ok with this change (in general, and the specific wording)? If so I'll open a PR.

![Screenshot 2023-05-10 at 1 46 30 PM](https://github.com/lookit/lookit-api/assets/9041788/a8aa81db-e492-4956-b0b9-1a041d525108)

**Comment by mekline** [comment]
Yes thank you!
