### ISSUE TITLE
Changes to Submission form

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#1201]
Some changes to both wording and form content of the Submission pop-up, designed to (a) not confuse new CHS users and (b) help us distinguish types of study in admin review.  

Summary of changes below: 

- Modified intro & peer review section, ideally with a bolded/distinguished header line
- Disclosures has the new section title + one change to the options (highlighted below) + new explainer text
- New section for external studies

-----

This will notify Children Helping Science admins that your study is ready for review. If you make additional changes, you will need to resubmit.

### Peer Review

Peer review is required for Internal studies (Lookit experiments) and strongly recommended for External studies.

Please list the researchers outside your group who have provided feedback on your study prior to submission, and the changes you made in response to peer feedback. (If this is a revision to an active study, list new changes made after approval).

[ Current Peer Review Box]

### Disclosures

Please note here any elements of your study that require additional review(see Terms of Use):

 Deception/withholding of information

 Sessions longer than 30 minutes

 **Internal studies only:** Departures from the standard Lookit template consent form or recorded confirmation statement 

 Incorporation of participant information from other sources (e.g. a school ID number)

 Collection of personally identifying information such as email addresses or zip codes

 Sensitive topics or questions (e.g. political subjects, race, bullying, mental health)

If you checked any of the boxes above, please describe below. These factors will *not* result in your study being automatically rejected; the most likely outcome is that we will email you separately to check on something:

[Disclosure box]

### Study status (External studies only)

If you are submitting a study that is already actively collecting data from participants, check the box below:

[ ] Data collection for this study has already started

**Comment by mekline** [comment]
@mekline will get a screenshot of the submit and resubmit fields to review & update text!

**Comment by okaycj** [comment]
@mekline 
> will get a screenshot of the submit and resubmit fields to review & update text!

Here are the submit images:
<img width="1552" alt="Screenshot 2023-05-11 at 1 15 00 PM" src="https://github.com/lookit/lookit-api/assets/44074998/e9eac311-50f9-4898-8547-1e81054a96fc">
<img width="1552" alt="Screenshot 2023-05-11 at 1 15 06 PM" src="https://github.com/lookit/lookit-api/assets/44074998/92e073e8-e305-4e57-ac77-87719bee1b22">

Here is the resubmit image:

<img width="1552" alt="Screenshot 2023-05-11 at 1 16 14 PM" src="https://github.com/lookit/lookit-api/assets/44074998/897c9123-33fa-4b49-8d36-1f7c3f16115c">

**Comment by mekline** [comment]
Let me know if you need more info @okaycj but to summarize:

The text I provided above moves the first sentence up to *above* the peer review box - it made sense when there was just that single line of text underneath, but now it seems to me it flows much better to describe the form with that sentence: 

*This will notify Children Helping Science admins that your study is ready for review. If you make additional changes, you will need to resubmit.*

Before going on to the info about the peer review box & subsequent items. 

For the resubmit box, let's leave it as-is, except please change Lookit to CHS. 

[NOTE: In the initial submit box, there are a few other uses of "Lookit" which SHOULD stay the same, because they are referring to the details of internal studies, not to the name of the platform/organization.  Yes this is confusing, thanks for bearing with me on this]

**Comment by mekline** [comment]
@okaycj can you let me know if this gives you everything you need?
