### ISSUE TITLE
Garden subsite - What is Project Garden?

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#1210]
Create a new site view, at the URL childrenhelpingscience.com/GARDEN/about

This is a subsite of the Project Garden pages.  It should have the same Project Garden nav bar at the top as the other pages.  

This one is formatted like the lookit.mit.edu/FAQ page, with some front matter. After the FAQ header, use the same format and expand/hide view as the primary FAQ page. 

Full text below: 

# What is Project Garden?

Project GARDEN is a research project by Children Helping Science and funded by the National Science Foundation. We have two goals: (1) to make it easier for families to participate in research and (2) to better understand how children develop over time in lots of different ways! 

Project GARDEN is a project aimed at understanding child development from many different angles: learning how to relate to their family and peers, how to problem solve, how to speak their family’s languages, and much more!

Each time you participate, your child will have the opportunity to follow a fun story involving a magical library and a friendly fennec fox named Fen!

# Frequently Asked Questions

## What is Project GARDEN?

Project GARDEN is a research project by Children Helping Science and funded by the National Science Foundation. We have two goals: (1) to make it easier for families to participate in research and (2) to better understand how children develop over time in lots of different ways! 

## Why is Project GARDEN important?

Project GARDEN is a project aimed at understanding child development from many different angles! Usually, a research project will only look at one or two specific areas of development, like specific math skills or specific vocabulary skills. In Project GARDEN, we look at how children grow in many different ways at once - learning how to relate to their family and peers, how to problem solve, how to speak their family’s languages, and much more! 

Every time you complete a Project GARDEN study, you will be helping science get a more complete picture of how children grow and develop!

## Is Project GARDEN for me?

Project GARDEN is for all families with 3- to 6-year-old children who are interested in development and education research and would like to help science by participating in lots of small studies! Our goal is for this experience to be engaging and fun for children and interesting and rewarding for caregivers. If you are interested in seeing how your child plays the research games or understanding more about how children learn and develop, you might find Project GARDEN a great experience for you and your family!

## How is Project GARDEN different from other studies on Children Helping Science’s website?

There are many exciting studies on Children Helping Science from around the world, and you can always participate in any studies that interest your family. Project GARDEN is a more specific set of studies on Children Helping Science. Keep reading to find out more!

## How does participating in Project GARDEN work?

Project GARDEN works by families participating in many short studies that, combined together, help us understand children’s development from many different angles. Each time you participate, your child will have the opportunity to follow a fun story involving a magical library and a friendly animated fox,  play research games designed to be fun for children, and receive a gift card. There will be at least 8 studies posted in the upcoming year, and most studies will take 10- 15 minutes to complete. You can choose whether to participate in each study, but the more studies that families complete, the better we can understand how children develop! If you complete all of the first set of 8 studies, you will receive an extra gift card as a thank you. You will then also have the opportunity to participate in more studies in the future!

## Why is it important to complete all of the studies?

The goal of Project GARDEN is to better understand the many different ways children develop using many quick, small studies instead of asking children to sit down for one really long study. Because of this, it’s very important to us for families to try to complete each of the first eight studies so we can look at these studies together! For example, you might do one study on how children think about different people’s perspectives and then another study on what kinds of words they know. Using both studies, we can see how what words they know might relate to how they think about different people’s perspectives. In another example, children might also complete the same study twice-once when they’re young and once when they're a bit older- to see what changed over time!

## Are you curious about participating but want to talk to a researcher first?

Email us at [project garden email] or sign up for a brief talk on [Microsoft Teams](https://calendly.com/utdthinklab/project-garden-question-session) with one of our Project GARDEN researchers and we’ll be happy to answer any questions! Sign-up slots are limited, but we will always respond to your emails within 7 business days. 

## Want to see what studies are like before you sign up?

There are other studies posted on Children Helping Science that are not part of Project GARDEN. You can visit the Children Helping Science [Studies Page](http://childrenhelpingscience.com/studies) to check out other studies to preview or try out another study before you decide if you’d like to participate in Project GARDEN!

**Comment by becky-gilbert** [comment]
@mekline do you know the email address I should use for this part?

> Email us at [project garden email] ...

**Comment by mekline** [comment]
Sorry about that, project.garden.study@gmail.com
