### ISSUE TITLE
Garden Subsite - Main page

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#1211]
Create a new site view, at the URL childrenhelpingscience.com/GARDEN/

This is the 'main' page for the new Project Garden pages. This and all 4 pages should have a nav bar at the top which is visible across these pages, as follows: 

Project Garden - childrenhelpingscience.com/GARDEN/
About - childrenhelpingscience.com/GARDEN/about
How to Join - childrenhelpingscience.com/GARDEN/participate
Start Now - childrenhelpingscience.com/studies/garden
The Scientists - childrenhelpingscience.com/GARDEN/scientists

(Note that the Start Now link goes to the existing lab page for project garden! See here: http://lookit.mit.edu/studies/garden)

Full content of the main page starts here: 

********

[Navigation bar: Project Garden | About | How to Join | Start Now | The Scientists]

[Project Garden logo: see Canva]

Welcome to Project GARDEN!

We are looking for families with children who are 3-, 4-, 5-, or 6 years-old to help us in **G**rowing and **A**dvancing **R**esearch in **D**evelopment and **E**ducatio**N** (**GARDEN**).  We have lots of studies that are designed to be engaging and often fun research games for children that are all about learning how children grow and develop in lots of different ways. Project GARDEN works by families participating in many short studies that, combined together, help us understand children’s development from many different angles.
 
Over the next 4 months, we will have at least 8 studies (10-15 minutes each) available in Project GARDEN, and families that do all 8 of our first studies will receive a $10 bonus. There will be additional study opportunities in the future! You can choose whether to participate in each study, but the more studies that families complete, the better we can understand how children develop!

[Fox-on-bridge image: See Canva]

Children who participate will experience a fun storybook where they will meet Fen, a fennec fox who is the new librarian for a magical GARDEN library. But Fen needs help finding it! As children finish research games, they will help Fen fill out a map and travel through many interesting locations on their way to the GARDEN library.

Click the links below to learn more about Project GARDEN!

[What is Project GARDEN?](childrenhelpingscience.com/GARDEN/about)

[New to Project GARDEN? Visit our How to Participate page!](childrenhelpingscience.com/GARDEN/participate)

[Project GARDEN Studies](childrenhelpingscience.com/studies/garden)

[Meet the scientists!](childrenhelpingscience.com/GARDEN/scientists)

**Comment by ianchandlercampbell** [comment]
Here is a link to the main graphic/image files we have for the website: [https://drive.google.com/drive/u/0/folders/1KVRkwsnigd44iHd3SK6taBMQCQdZmg6c]
