### ISSUE TITLE
"Mangage Account" on both Staging and Live Lookit

### ISSUE THREAD

**Issue by ianchandlercampbell** [lookit/lookit-api#1225]
Managing account for experimenters (possibly for families as well?) says "Mangage Account" instead of "Manage Account"

![image](https://github.com/lookit/lookit-docs/assets/75502403/1e1c6e72-cd85-4a02-b009-d1ead54a8658)

**Comment by becky-gilbert** [comment]
Thanks very much for putting this in an issue @ianchandlercampbell!

Fixed via [de03147](https://github.com/lookit/lookit-api/commit/de031478d1dabf3c6afe438e50e191cca6558ad2)

![Screenshot 2023-05-23 at 10 36 54 AM](https://github.com/lookit/lookit-docs/assets/9041788/71623098-55c9-4ee6-8e20-df272fd1fe8b)
