### ISSUE TITLE
Research how to capture experiment jsPsych data

### ISSUE THREAD

**Issue by becky-gilbert** [lookit/lookit-api#1236]
While we have inlings of how to record jsPsych experiment data, we're interested in the most natural solution possible.  To facilitate this, we will set up a meeting with the creators of the project and suss out a solution. 

# Requirements
1. New response created on start of experiment. 
2. Response is updated on new data available.
3. Mark response as completed on experiment finish. 
4. Create CHS specific plugins (Issue to come soon...)
5. Address data structure in experiment and/or data handing in lookit-api to provide the researcher a normalized experience. 

# Documentation
After making the implementation decisions, we may need to update the [Lookit architecture documentation page](https://lookit.readthedocs.io/en/develop/contribute-architecture-overview.html) (tracked in a separate issue here: https://github.com/lookit/lookit-docs/issues/319) as well as our internal documentation.

**Comment by okaycj** [comment]
I agree with the summation above, but I do think that what exactly needs to be done should be detailed in either this issue or a collection of issues.

**Comment by becky-gilbert** [comment]
Closing this as it is all covered by this larger scoping issue: #1324
