### ISSUE TITLE
Project Garden - new consent template

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#1266]
The project GARDEN team needs a new consent form; there are a number of small changes that have been made & in particular ordering of sections has been modified, so that the easiest thing to do at this point is to create a separate template rather than try to enumerate changes. 

Ian helpfully provided the complete text of the Garden template (with ordering & suggested section names, plus correspondence with `consent_005` parameters) here: https://docs.google.com/document/d/1dE-OkyvQqbV9cSx1uT-IW3wcVI1p5xAX2WV5UPMg-aU/edit#heading=h.hm29j11x1cu7).  It has a readme of desiderata at the top; we may need to discuss some of these or add additional ones. 

## Notes

-  I was wrong, institution is already an editable parameter - YAY!
- Because most sections have been changed from the defaults, and some-but-not-all sections may be modified by the individual GARDEN studies, Ian proposes making all sections editable by the researcher.  Sections that researchers are not supposed to modify are in blue in the GARDEN handbook, but not marked in the attached google doc at the moment. But even if not meant to be edited, the text of these sections are often *different* from the content of `consent_005`.
- However, if sections are non-parametrized in `consent_005` and not-to-be-modified in consent_GARDEN, it might actually be easier to keep that the same here (with the new text).  Likewise for phrase-level parameters like `PIName`. Let's talk about which course is best.  
- From Ian: The numbers in front of each section are for reference– they should not be in the consent form displayed to families.
- From Ian: Any deviations you see from the consent_005 are intentional. For example, benefits and payment are two separate sections. Please reach out if you have any questions.
- User re-ordering sections is out of scope for this issue 

## Acceptance criteria

- [ ] There is a new option for the `template` parameter of `exp-lookit-video-consent`, called `consent_GARDEN`
- [ ] Providing this template with only the required parameters (e.g. `PIName`) produces the text in the attached google document (i.e. with all defaults set as described) in the order presented.
- [ ] Parameter names that correspond to existing chunks have the same names, Ian has provided suggested names for those which are new or split up
- [ ] All text that appears in the consent form is parameterized and each section is editable by the user.  [POSSIBLE ALTERNATIVE - ALL SECTIONS ARE NAMED IN THE DOCUMENTATION, BUT SOME ARE MARKED AS NOT-EDITABLE. 
 HOWEVER, IN EITHER CASE AVOID 'SECRET' PARAGRAPHS THAT ARE NOT MENTIONED ANYWHERE IN THE DOCS.] Where there are phrase-level parameters, [DECIDE COURSE OF ACTION]
- [ ] [TENTATIVE] All sections have corresponding `XXX_header` parameters which can be edited.  (The default text of these headers should be as given in the google doc) - may not be true if not all paragraphs are set editable. 
- [ ] Documentation for the `consent_GARDEN` template (and template-only parameters) should *not* be mixed into the standard documentation page, because it should not be used by the community at large.  But it should be linked/available, maybe as a new page on the RTD docs. 
- [ ] Documentation for the main consent frame probably has opportunistic examples for improvement, and please do take these opportunities where possible. In particular, some parameters are provided by the researcher in the frame, and some are pulled from the DB record of the study itself (such as the length of the study) - this is often not transparent. 
(In Ian's text, for instance, there are sections like: 

```This is the [study.name] run by [lab name] at [institution] as part of Project GARDEN...In this study, [brief one-sentence description of the study].```

For the bracketed points, it would great for all parameter names to be included in the main documentation, even if they are not editable in the consent form itself.  For instance

(use whatever the actual internal parameter name is) `study_length`: The length of the study, automatically pulled from the study form.  This appears in a sentence like "This study will take [study_length] to complete", at a few places in the consent form, exact wording depending on the template.  To change the study length, go to....

**Comment by becky-gilbert** [comment]
> Documentation for the consent_GARDEN template (and template-only parameters) should not be mixed into the standard documentation page, because it should not be used by the community at large. But it should be linked/available, maybe as a new page on the RTD docs.

@mekline @ianchandlercampbell would it be ok to put the docs in a markdown file that just lives on Github (rather than on the RTD docs site)? This would mean I can avoid the hassle of adding a new page to RTD, and it would make it harder for non-GARDEN researchers to stumble upon it. It would still have a permanent link and be in a readable format.

**Comment by mekline** [comment]
Sounds good to me!

**Comment by ianchandlercampbell** [comment]
That seems reasonable (and I love a great markdown)!
