### ISSUE TITLE
Change domain in the default value for a study's Exit URL

### ISSUE THREAD

**Issue by becky-gilbert** [lookit/lookit-api#1274]
The researcher's study edit form (Study Ad and Recruitment page) automatically populates the 'Exit URL' field with 'https://lookit.mit.edu/studies/history'. This is true regardless of what domain the user is on when they create the study (either of the production domains, staging, or localhost).

https://github.com/lookit/lookit-api/blob/90c2e5ad1fe1c5480607a180a0f33d46addd4afa/studies/models.py#L314

![Screenshot 2023-09-26 at 2 06 30 PM](https://github.com/lookit/lookit-api/assets/9041788/93b6558a-0569-4078-a65b-ce5646d51c6c)

If we are assuming/hoping that families will use the Children Helping Science domain, then we should consider changing this default URL to be that same Children Helping Science domain, so that the family isn't directed to a different domain after completing a study, which could be weird/confusing for them. Or a better solution might be to create the study's default Exit URL using the value of `SITE_DOMAIN` from the project settings.

**Comment by becky-gilbert** [comment]
@mekline should we add this to the upcoming production release #1278 ? (It's a very quick change.)

**Comment by msheskin** [comment]
Hello! I was about to create a new issue for this topic but I think I can probably leave a comment here instead and then you can let me know if you want me to make this a different issue.

I think there is something here that is NOT just "researcher QOL". Specifically, if a family is logged into ChildrenHelpingScience.com and then the exit URL goes to https://lookit.mit.edu/studies/history they might NOT be logged in at the Lookit URL. And it is possible they have their login credentials saved in their browser for CHS but not for Lookit. The same is true in reverse (a family logged into Lookit who does a study that drops them into https://childrenhelpingscience.com/studies/history might not be logged in there).

This seems like it matters across the site, but will also matter in particular for the GARDEN sequence. We deeply want them to see "the next study" when they are done with each study in the sequence, and so are dropping them into EITHER https://lookit.mit.edu/studies/garden/ OR https://childrenhelpingscience.com/studies/garden/ -- but which one should be the exit URL?

In Becky's Sept 26 comment there is the note "Or a better solution might be to create the study's default Exit URL using the value of SITE_DOMAIN from the project settings." and I'm not sure what "SITE_DOMAIN from the project settings" means, but I think the most elegant solution would be if the exit URL could pay attention to the current URL the family is on. Specifically, the researcher indicates just "/studies/garden" as the exit URL, and then Lookit pays attention to whether the family is at Lookit or CHS URL to fill in the first part.

**Comment by becky-gilbert** [comment]
@msheskin just wanted to let you know that we haven't forgotten about this problem! I'm going to restrict the scope of this particular GH issue to just setting the domain of the Exit URL to match the domain that the researcher is currently using. 

Alongside this, we are trying to fix some of the domain/branding consistency issues (lookit.mit.edu vs childrenhelpingscience.com), including this important exit URL / login issue that you've raised. It's not possible to have log in that works for multiple domains, and it would be difficult to use the _participant's_ domain when they're redirected to the study's exit URL. The best solution we've come up with is to create an automatic redirect from the lookit domain to childrenhelpingscience. This means that all existing lookit links will still work, but the URL will automatically change to the CHS domain when someone tries to visit a lookit.mit.edu page. We will be testing this out on the staging server soon to make sure that there aren't any unintended consequences. I can let you know when it's working on the staging site so that you can test things out, if you'd like. I'll also open a separate issue to track this and update this comment with the link.
