### ISSUE TITLE
Delete or make unavailable withdrawn data

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#129]
*Pain point*: At the conclusion of any study, parents select a privacy level for the video (in-lab use only, scientific/educational sharing allowed, or publicity use allowed) and whether data may be shared on Databrary. Parents also have the option to withdraw video data entirely. This option is rarely used, but is important because we are filming in families’ homes and sensitive information could be accidentally disclosed during recording. When a parent selects that they would like to withdraw video, this information is included in information given to researchers, but the video is not automatically deleted - that is left to the researcher. This introduces unnecessary potential for human error.

*Acceptance criteria*: Video from any session that a parent withdraws video from is deleted from all Lookit storage automatically, and is not available to the researcher running the study. Other data from the session is still available.

*Implementation notes/Suggestions*: Ideally we might introduce a slight delay (e.g. 1-7 days) before deleting video from Lookit servers, in case the parent withdrew accidentally and asks us to restore the video; however, this is likely much more trouble than it's worth.

**Comment by Datamance** [comment]
- [ ] add withdrawal info to consent manager

**Comment by kimberscott** [comment]
[] add withdrawal field to response data as used for csv/json download and 'individual responses' display, in line w/ completed field

**Comment by Datamance** [comment]
Ready to close when you are

**Comment by Datamance** [comment]
🍾 🎉 🎈
