### ISSUE TITLE
Integrate jspsych responses with app UI

### ISSUE THREAD

**Issue by bleonar5** [lookit/lookit-api#1316]
# TL,DR

Currently, response data from jspsych studies is not visible through the same interface as EFP. Response data and from jsPsych studies should visible and available for download on the "Individual Responses" and "All Responses" pages. 

Also, any response info that is displayed to researchers on those pages should also be visible with jsPsych studies.

## Individual Responses: response info and download button

<img src="https://github.com/user-attachments/assets/7e937821-5a09-4234-894f-1ad75fa1ee6a" width="440" height="420">

<img src="https://github.com/user-attachments/assets/a9d912cf-4f52-456d-989d-8ac4a588cbf3" width="440" height="150">

## All Responses: all download buttons should produce the relevant data

<img src="https://github.com/user-attachments/assets/462ecb49-f366-4cdb-b780-8f279399d73e" width="697" height="406">

## Relevant lookit-api views

- StudyResponsesList
- StudySingleResponseDownload
- StudyResponsesAll
- StudyResponsesCSV
- StudyResponsesDictCSV
- StudyResponsesFrameDataCSV
- StudyResponsesFrameDataDictCSV

## Info displayed on Individual Responses page

The Individual Responses view (`StudyResponsesList`) currently displays the EFP frame sequence and other info from the response object/data. This is shown in the "Response details" box for each individual response. For jsPsych studies, we also want to display all of the relevant summary info that comes from the response object/data in that  "Response details" box. 

The list of columns that are shown in the "Response details" box is below and linked [here](https://github.com/lookit/lookit-api/blob/a75fe88768eec65ee6424ffcdafcb1e5a8b20682/studies/models.py#L836-L863). Some of the `response__` info will already be available in the response objects for jsPsych studies (ID, UUID, date created, etc.). However, some of these things are columns in the Response table that need to be set directly via the jsPsych experiment or pulled out of the jsPsych `exp_data`: `completed`, `withdrawn`, `parent_feedback`, `response__birthdate_difference`, `response__video_privacy`, `response__sequence`. For some of these values, the Response model is set up to locate the exit frame in the response data and grab the relevant info out of it (see [here](https://github.com/lookit/lookit-api/blob/a75fe88768eec65ee6424ffcdafcb1e5a8b20682/studies/models.py#L1110-L1151)). 

```python
    def columns_included_in_summary(self):
        if self.study_type.is_ember_frame_player:
            return [
                "response__id",
                "response__uuid",
                "response__date_created",
                "response__completed",
                "response__withdrawn",
                "response__eligibility",
                "response__parent_feedback",
                "response__birthdate_difference",
                "response__video_privacy",
                "response__databrary",
                # etc. 
            ]
```

**Comment by becky-gilbert** [comment]
Closed as completed via #1454 #1457 #1465 #1469
