### ISSUE TITLE
Responses with consent via `survey-consent` frame are not available to researchers

### ISSUE THREAD

**Issue by becky-gilbert** [lookit/lookit-api#1317]
**Description**

Responses to studies that use the `survey-consent` frame for consent are not becoming available to researchers, because they are not marked as having a consent frame (all are `completed_consent_frame: false`) and therefore they do not become available to researchers for a consent ruling. This is true despite the frame being correctly identified as consent (`frameType: "CONSENT"`). 

**Expected behavior**

Responses that include the `survey-consent` frame should become available to researchers.

@mekline questions for you about how consent approval should work with `survey-consent`: 
1. Should all responses with a `survey-consent` frame appear in the study's 'Review Consent' section (even though at that point the researcher has no way of seeing the response to the consent question)?
2. Should all responses with a `survey-consent` frame appear in the study's 'Study Responses'  section (regardless of how the participant responded to the consent question)?
3. Do we need to add in some code to automatically extract the response to `survey-consent` frames and either (a) present it to the researcher in the 'Review Consent' section or (b) have the lookit-api check the value and use that to automatically move consented responses to 'Study Responses' section? This option will take longer to implement, and (b) will take longer than (a).

**Implementation notes**

The Study model's `judgeable_responses` property just filters the study responses on `completed_consent_frame: true`, and then the responses that are available to researchers come from the subset of judgeable responses that have been approved. So I think we just need to get the responses with survey-consent frames to be marked as `completed_consent_frame: true`. There might also be an issue with filtering responses based on the presence of video for the purpose of detecting/judging consent.

**Comment by mekline** [comment]
Another likely symptom of the same problem, from an email with a family (I told them there is a technical difficulty and they'll see the studies moved over shortly via the manual process):

"My son recently completed several studies (Mind Magic, What Does Most Mean?, etc) but I notice none of them were moved to completed studies and still appear when filtered for studies not completed."

**Comment by mekline** [comment]
I think #2 is the best course, so long as we can make it clear to researchers that they still need to screen on the question and re-reject consent if needed!

**Comment by mekline** [comment]
(So for instance, they will appear (with no video) under the 'approved' consent page, right? Could there be something like a banner explaining that these are counted as approved because the participant clicked to continue from that page, but researchers should confirm in the data and reject the consent if needed.

**Comment by becky-gilbert** [comment]
> So for instance, they will appear (with no video) under the 'approved' consent page, right? 

Yes, if we want them to. We could just have the consent judgment page ignore these cases, but I think it's better to have them listed there so that researchers can reject any that should be rejected.

> Could there be something like a banner explaining that these are counted as approved because the participant clicked to continue from that page, but researchers should confirm in the data and reject the consent if needed.

Yes!

**Comment by mekline** [comment]
OK, if it's tractable then I think this banner should be present whenever
an 'accepted' survey-consent session is active on the consent page

**Comment by becky-gilbert** [comment]
@mekline could you please give me some feedback on this? Here's what I've done:

- Marked responses in the list on the left with `[Survey consent]` (similar to how preview responses are marked)
- Added some yellow warning text in the 'video information' area explaining that the response contains survey-consent, and the researcher should accept the consent but then verify it in the data

And a few other UI changes:
- Put all the elements in the video section (middle column) in a card with a 'video' heading, to match the other columns
- Add a 'comments' label for the comments section (middle column, below the video area)
- Highlight the entire 'video information' box above the video, rather than just the text, when there is a warning
- In the response list on the left, remove the 'N/A' when there are no comments
- Add a hover style (slight background color change) to the responses in the list on the left, to make it clearer that they are clickable elements

Here's what the page looks like when it first loads. These are responses pending judgment and do not have comments. The second response in the list contains a survey-consent frame.

<img width="1316" alt="consent-initial" src="https://github.com/lookit/lookit-api/assets/9041788/18991df4-87ff-41c9-ab3b-5d8e7d6438ea">

Here's what the page looks like with a selected response and no video found.
<img width="1316" alt="consent-no-video" src="https://github.com/lookit/lookit-api/assets/9041788/96acdb0d-1910-48e9-9a14-5e005af4bca1">

Here is a selected response that has no video and a survey-consent frame. I decided to keep both messages because it's possible for a study to contain both a video-consent/assent and a survey-consent frame. This means it's possible for us to want to show the 'survey consent' warning to researchers with and without the presence of a consent video for that same session.

<img width="1316" alt="consent-survey" src="https://github.com/lookit/lookit-api/assets/9041788/63a79b96-b614-496f-8d77-13a3b3a6f167">

Here's an example showing a response in the list on the left that contains a comment. When there are no comments associated with a response, this small italicized text is omitted (rather than showing "N/A").

<img width="1316" alt="consent-comment" src="https://github.com/lookit/lookit-api/assets/9041788/844e68fb-d7e7-4150-8988-b4d33a4bca67">

And here's a video showing the hover styles over the response list.

https://github.com/lookit/lookit-api/assets/9041788/f10c1682-f283-46a6-99eb-b8baf571b11d

**Comment by mekline** [comment]
Okay, this all looks great to me, and very good catch on both the 'video absent' vs survey consent and the study-with-both-kinds issue.  How does this compare to how we treat video assent?  These are another case where there can be two videos for researchers to judge, but I'm not sure on the details of how those appear - do the arrows below the video control that, or skip you to the next response from your left hand column? 

Structural question - is the comment-box per response, or per consent type? (IE if there's a video-assent video, is there still a single comment, or is a separate comment field created?)

Other than checking the flow for the case of 'video-consent + video-assent' and maybe 'video-assent + survey-consent', I'm happy with how everything looks, and just have a suggestion for the message on survey-consent:

This response contains a survey consent frame. To review whether consent is valid, (1) check the frame sequence below (if you set up frame logic for consenting vs. non consenting participants), or (2) mark the response as 'accepted' here, then go to the Study Responses page to review survey answers on your own.

**Comment by becky-gilbert** [comment]
@mekline great questions.

> How does this compare to how we treat video assent? These are another case where there can be two videos for researchers to judge, but I'm not sure on the details of how those appear - do the arrows below the video control that, or skip you to the next response from your left hand column?

If there is both video consent and video assent then the researcher sees both videos for the same response session (selected on the left), and they use the arrows under the video to navigate among however many consent/assent videos exist for that session. 

> Structural question - is the comment-box per response, or per consent type? (IE if there's a video-assent video, is there still a single comment, or is a separate comment field created?)

The comments are per response session. If you type a comment in the box under the video, it does not change as you navigate among videos for that session. The comment is saved once the consent judgment for that response is changed to accepted/rejected and saved, and then it appears in the box on the left for that session.

Let me know if this affects your thoughts on my changes listed above!

> This response contains a survey consent frame. To review whether consent is valid, (1) check the frame sequence below (if you set up frame logic for consenting vs. non consenting participants), or (2) mark the response as 'accepted' here, then go to the Study Responses page to review survey answers on your own.

Thank you! (I still need to put in a PR for review so there will be another opportunity to see screenshots and edit this text.)
