### ISSUE TITLE
Set up Google search console and Analytics

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#135]
*Pain point*: We need to increase the userbase but don't have information about how many people are visiting the site from what sources in order to evaluate advertising efforts.

*Acceptance criteria*: We can see traffic to the site over time, broken down by audience and how they got there if possible.

*Implementation notes/Suggestions*: Setting up Google search console & analytics would probably work well for our purposes, but can consider other options.

**Comment by kimberscott** [comment]
For Google AdWords, if we wanted to track signups and participation linked to advertising, the boilerplate is below.

Would we be able to set this up to happen for prod only? 

1. In the `head` of the base page (or in our js) add:

```
<script async src="https://www.googletagmanager.com/gtag/js?id=INSERT_ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'INSERT_ID');
</script>
```

2. On pages where we want to track an action - signup, participate - include the following, and call `gtag_report_conversion`


<script>
function gtag_report_conversion(url) {
  var callback = function () {
    if (typeof(url) != 'undefined') {
      window.location = url;
    }
  };
  gtag('event', 'conversion', {
      'send_to': 'INSERT_EVENT_ID',
      'event_callback': callback
  });
  return false;
}
</script>

**Comment by okaycj** [comment]
Make sure to track `sign up` and `participation` (Visiting the experiment proxy page)
