### ISSUE TITLE
Scoping Lookit API Release Week of 03-25-2024

### ISSUE THREAD

**Issue by ianchandlercampbell** [lookit/lookit-api#1365]
### Summary

We are planning a Lookit API update to be released during the Week of 03-18-2024. This update will include changes to the CHS domain (redirecting from lookit.mit.edu to childrenhelpingscience.com for all cases) and multiple changes to email systems in order to comply with new requirements from multiple email clients in response to new FTC regulations:

### Details

Domain/website:

- Domain redirect 
  - Issue: #1352
  - PR: https://github.com/lookit/lookit-orchestrator/pull/49
  - QA: https://github.com/lookit/lookit-api/issues/1355
  
  The following two issues are part of the domain redirect because they use the `BASE_URL` variable from the settings, which will change from Lookit to CHS with the domain redirect:
   - Changing links in recruitment emails to CHS instead of Lookit 
     - Issue: #1336
     - PR: https://github.com/lookit/lookit-orchestrator/pull/49
    - Change the domain for a study's default exit URL from lookit.mit.edu to childrenhelpingscience.com
      - Issue: https://github.com/lookit/lookit-api/issues/1274
      - PR: https://github.com/lookit/lookit-api/pull/1353

Email Systems

- Sending emails from the MIT domain instead of impersonating lab emails 
  - Issue: #1356
  - PR: #1357
  - QA: https://github.com/lookit/lookit-api/issues/1358
- One-click unsubscribe 
  - Issue: #1350 
  - PR: #1349 
- New Contact Us footer 
  - Issue: #1364 
  - PR: #1368

MBAH

- internationalization and Japanese translations 
  - PR: #1345
- Linting 
  - PR: #1369

**Comment by becky-gilbert** [comment]
Closed via #1366
