### ISSUE TITLE
Incorrect time conversion from UTC to EST

### ISSUE THREAD

**Issue by sradifera** [lookit/lookit-api#1367]
![Screenshot 2024-03-13 at 1 52 29 PM](https://github.com/lookit/lookit-api/assets/127788047/9884d86e-dcea-4f2a-b48e-8d03880d971e)
![Screenshot 2024-03-13 at 1 52 35 PM](https://github.com/lookit/lookit-api/assets/127788047/dbe2fff9-3b95-4d4c-9e4c-7c97b6976fcd)
![Screenshot 2024-03-13 at 1 53 17 PM](https://github.com/lookit/lookit-api/assets/127788047/42affa5b-539f-4f04-84e4-6be93c8179e1)

When reviewing spam reports I need to view the consent video of the participant in question. The researcher who makes the report provides the date created of the consent video which to my understanding is in UTC. To find and review the consent video on my end I need to convert this time into EST since I am in Cambridge, MA. In the example I show int he screenshots, the conversion is an hour (and a day?) off than what google tells me is the correct conversion from UTC to EST. Not sure if this is a problem with my machine (macOS) or the site.

**Comment by okaycj** [comment]
@sradifera 

Could you provide the experiment that this example was pulled from?

**Comment by sradifera** [comment]
@okaycj here's the link: https://lookit.mit.edu/exp/studies/3112/

**Comment by okaycj** [comment]
@sradifera 

To confirm that the date/time was correctly converted from UTC to EST I used a browser's Javascript console.   Instantiating a Date object with the UTC string from the "Data Sessions" card provides an EST date/time that matches what has been selected in the "Responses" card. 



<img width="514" alt="Screenshot 2024-04-16 at 9 27 38 AM" src="https://github.com/lookit/lookit-api/assets/44074998/6a72571d-8511-455d-8ef7-78970643a84b">
<img width="347" alt="Screenshot 2024-04-16 at 9 31 43 AM" src="https://github.com/lookit/lookit-api/assets/44074998/8a615b67-2a43-4b4e-9646-7f67a1d9abbb">
<img width="1293" alt="Screenshot 2024-04-16 at 9 31 24 AM" src="https://github.com/lookit/lookit-api/assets/44074998/4a5118e2-f02c-4f82-9a9e-cb418fa16dba">
