### ISSUE TITLE
Psych-DS data downloads

### ISSUE THREAD

**Issue by bleonar5** [lookit/lookit-api#1374]
# TL;DR
We want researchers to be able to download their result data in a format that is already Psych-DS compliant

# Narrative
Ideally this should probably be forced, but maybe it's best if it's an option. 
If data is always downloaded one study at a time, need to think about options/possibilities for compiling into datasets.
Think about potential clunkiness/redundancy of downloading a new psych-ds dataset for every single response download.

**Comment by becky-gilbert** [comment]
Sounds great! A few thoughts:
- I like the idea of it being the only available format, unless there's a 'breaking' change. I think any changes that would break a researcher's workflow would have to be related to the response data format (column names etc., which I don't think you'll touch?) and maybe file names. 
- One thing to think about is that researchers often download one response at a time (is that what you meant by "one study at a time"?). So if a researcher's workflow is to download each response as it comes in, how do we get them to end up with a Psych-DS-compliant dataset? Maybe this isn't something to worry about in the first pass, but worth thinking about.
