### ISSUE TITLE
Scoping: Query info for a grant

### ISSUE THREAD

**Issue by okaycj** [lookit/lookit-api#1403]
A research lab has asked us if we could provide information for the following statement:

"To date, XXX labs have used our platform to run XXX studies and we have XXX children aged 8-13 years enrolled in our registry"

Would this be an easy thing to query? Or should we offer something similar, but more tractable like "currently XXX children aged 8-13 years are registered on Children Helping Science"?

**Comment by okaycj** [comment]
### Number of Labs

### SQL Query

```sql
select count(*) from studies_lab sl
where sl.approved_to_test
```

### Result

305

**Comment by okaycj** [comment]
@ianchandlercampbell To the best of knowledge, this should be what you're looking for.  Let me know if you have any questions.

**Comment by ianchandlercampbell** [comment]
@okaycj Perfect, thank you! I'll let the researchers know.
