### ISSUE TITLE
Check why it takes so long to download data

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#175]
*Pain point*: Fetching data via the API, e.g. "all sessions of this study completed by this child" as fetched at the start of any study, is quite slow.

*Acceptance criteria*: Fetching all user data (or say 3000 records) takes <15 seconds, OR some more reasonable amount of time if that's unrealistic. (It seems like not a huge amount of actual data but I don't deal with databases much.) Fetching records of all 50 sessions of a study completed by one child takes <5 seconds. 

*Implementation notes/Suggestions*: Maybe we don't need data paginated in groups of 10 by default in the API? Is it properly indexed?

**Comment by Datamance** [comment]
I think this is fixed for this endpoint https://lookit.mit.edu/api/v1/responses/ <-- which other API facets do we need to cover?

**Comment by kimberscott** [comment]
/users/ and /children/ are the ones that are surprisingly slow when using the API here - e.g. to fetch account data (a page at a time, ~365 pages on prod) takes >2 minutes. That's not terrible, it just surprises me given the amount of information that's actually being downloaded.

**Comment by Datamance** [comment]
That _is_ terrible and we should fix it 🛠

[ ] /users/
[ ] /children/

**Comment by Datamance** [comment]
These are fixed now
