### ISSUE TITLE
Add 'compensation' field to study model

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#205]
Pain point: Info about compensation has to be lumped into the study description or purpose, making unwieldy descriptions.

Success criteria: Compensation info displayed separately on study detail page to participants.

Implementation notes: Add a 'compensation' field to the study model; this can just be a string (like study purpose or display). Show it on the study detail page (to participants) and study edit page (to researchers).

**Comment by kimberscott** [comment]
Arbitrary definition for now, for flexibility - this is just a quick fix until we actually support compensation directly; not many researchers will ever use it so it's not worth trying to come up with a general description of compensation schemes. I just want the information to be a little easier for participants to see - see https://lookit.mit.edu/studies/cfddb63f-12e9-4e62-abd1-47534d6c4dd2/ for current example of a big lump of "description" text including compensation.

**Comment by Datamance** [comment]
Are we good to close this out?

**Comment by kimberscott** [comment]
Yep!

**Comment by Datamance** [comment]
🎉 🎂 🎈
