### ISSUE TITLE
UI improvements for study edit views

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#208]
A) View - Edit study

~1) Add a preview button that just links to the study preview at bottom of "Study editor" section. Button should be disabled if preview dependencies aren't built yet, w/ help text saying to build them in order to preview study.~

~2) Add some help text to the "Change study type & dependencies" section to explain what this is & how it works. (Kim can provide text)~

~3) Display preview dependency build status under "Change study type & dependencies"~

~4) Format minimum & maximum age in days/months/years as side-by-side fields and restore help text explaining to researchers how these are actually used to calculate an age range in days~

~5) A warning shows up when saving changes to a study that has already been approved - "Are you sure you want to modify the JSON [...]?" Since this is triggered by *any* changes, not just JSON, change warning text to "Are you sure you want to modify the study [...]?"~

~6) Move "Manage Researchers" to the Study Detail view~

~7) Use modal instead of banner message for invalid JSON error upon saving as this is easy to miss.~

~8) Check that commit SHAs are valid (or blank) upon saving dependencies & prevent save w/ warning if not~

~9) If commit SHA is blank and gets resolved to the latest master commit, store that commit sha in the study so researchers can tell which version they're using! See problem introduced here: https://github.com/lookit/lookit-api/commit/1c6399c9b3fe560e323c2c3d4e71c6f6b19c9830#commitcomment-31840951 Ideally we would fully fold in #120~

B) View - Study detail

1) "Previewed:" -> "Preview dependencies:" to be directly analogous to "Dependencies" status

2) Move "Build study" button next to "Dependencies: built/not built" for clarity

3) Move "Edit study," "View responses," "Email participants," & "Clone study" all in one area where "View responses" and "Clone study" are now, instead of putting edit/email up top

4) Display study participation URL (i.e. lookit.mit.edu/studies/[STUDYID]/) in addition to just the study ID so researchers can find it w/o going back through email notifications

5) Hide comments section unless selected action is "reject" (?)

6) Possibly: use modal instead of banner message for build action ("You will be notified..") and for "activate" error (if dependencies are not built) b/c it's easy to miss these at the top of the page

~7) Log should say something like "Dependencies built" instead of "deploy"~

8) Proposed changes to study state change names:
   "Activate" -> "Start data collection"
   "Pause" -> "Pause data collection"
   "Submit" -> "Submit for review"
   "Deactivate" -> ??? depends what this does exactly, but as is it reads as the opposite of "Activate" which is not true. From the standpoint of a typical researcher is this "Delete"? Is "archived" actually different from "deactivated"?

[Scan 2019-01-03 13.56.12.pdf](https://github.com/lookit/lookit-api/files/2725001/Scan.2019-01-03.13.56.12.pdf)

**Comment by kimberscott** [comment]
It appears study thumbnails are being saved correctly on staging (just needed to reupload them so they go to the right place).

**Comment by kimberscott** [comment]
Could also fold in #205

**Comment by Datamance** [comment]
@kimberscott reminder for A7 that we should create a new issue addressing the less-than-ideal user experience around JSON authoring. Until then we've just improved the error messaging

**Comment by kimberscott** [comment]
Current testing notes (checked list above): 
- Trying to save state hangs for me when testing locally - expected? I can't submit, pause, etc. State DOES get correctly changed to rejected if changes are made.
- The default "None" text that goes in the addons & player SHA fields in 'Edit Study' is treated as an invalid SHA and prevents save. Need to either change the default to an empty string rather than "None" or accept both empty string and "None" as resolving to latest default branch commit.
- I can't add a researcher locally despite having study admin permissions (have not yet been able to test changing researchers' permissions between admin and read, or test that with only study read permissions I can't add/remove researchers or change permissions)
- Remaining todo: 
   - Rename "deactivate" and other actions under "change state" for clarity
   - Clearly display participation URL on study detail view. There is a text box that shows up only when the study is private (non-discoverable) and active, showing the correct link (although the 'copy' button doesn't work for me). Can this actually just be shown regardless of discoverability and state, under "Discoverability"? E.g., if discoverability is private, display "When active, study will not be listed at http://localhost:8000/studies/ but will be accessible to participants at http://localhost:8000/studies/81933db0-3dc8-4771-8841-2e0c9bda67bc/." If discoverability is public, display "When active, study will be listed at http://localhost:8000/studies/ and accessible to participants at http://localhost:8000/studies/81933db0-3dc8-4771-8841-2e0c9bda67bc/" (It's useful to researchers to have the link available before actually starting data collection, esp. since they don't automatically know they'll get it later)
   - Add link to https://lookit.readthedocs.io/en/develop/experimenter.html#editing-study-type in the help-text for commit SHAs

**Comment by Datamance** [comment]
I believe we can close this out with the follow up of a re-assessment and potential redesign of the state flow - @kimberscott does that sound right or am I missing something?

**Comment by kimberscott** [comment]
Would it be possible to add the short help-text to the state change dropdown? Other than that looks great.

**Comment by Datamance** [comment]
@kimberscott I'll let you take care of the above item in `origin/208-ui-improvements-study-edit-kim-review` - that way we keep it all in one PR. Let me know when you want me to review and I'll pull your branch down
