### ISSUE TITLE
Static and media paths "double up" in staging

### ISSUE THREAD

**Issue by Datamance** [lookit/lookit-api#209]
I believe this was happening with earlier deploys, but you can see in the screenshots linked below what I'm talking about:

<img width="327" alt="screen shot 2019-01-03 at 2 13 52 pm" src="https://user-images.githubusercontent.com/8699411/50656614-d3225e00-0f61-11e9-8a4f-be29c62e32c0.png">

It appears that there's something amiss with how we serve static files in staging. I'm not seeing the same pathology in prod, so I've apparently introduced something by way of a mismatch between my local env and staging.

**Comment by kimberscott** [comment]
I'm not able to reproduce a thumbnail getting saved and then reverting to the original (broken) path - currently https://staging-lookit.cos.io/exp/studies/55/ is showing the newly-uploaded baby-and-dog photo

**Comment by Datamance** [comment]
Right, because it's uploading all the static assets to the targeted place now, based on static settings. I've actually found the problem:

`(py36)  ricorodriguez  ◰³ py36  ~/P/lookit-api   develop  git diff 03ff53b5f6090616d45a93f122e24147b16e1077 project/settings/defaults.py`      
```                                                                                                                                                             Thu Jan  3 14:54:18 2019
diff --git a/project/settings/defaults.py b/project/settings/defaults.py
index d801f3b..355d666 100644
--- a/project/settings/defaults.py
+++ b/project/settings/defaults.py
@@ -14,6 +14,11 @@ import os
 from django.contrib.messages import constants as messages
 import raven

+# TODO: deliberate then choose on a methodology for dynamic class selection,
+# i.e. for Storages. Should we choose the storages here, or defer that
+# to initialization of the Storages module?
+MODE = 'prod'  # Overridden by local settings.
+
 # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
 BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
 # root path for ember builds
@@ -266,16 +271,16 @@ CORS_ORIGIN_WHITELIST = [h for h in os.environ.get('CORS_ORIGIN_WHITELIST', '').

 if os.getenv('GOOGLE_APPLICATION_CREDENTIALS'):
     # if we're trying to use cloud storage
-    STATICFILES_LOCATION = '/static'
+    STATICFILES_LOCATION = 'static'
     STATICFILES_STORAGE = 'project.storages.LookitStaticStorage'
     STATIC_URL = os.environ.get('STATIC_URL', '/static/')

-    MEDIAFILES_LOCATION = '/media'
+    MEDIAFILES_LOCATION = 'media'
     DEFAULT_FILE_STORAGE = 'project.storages.LookitMediaStorage'
     MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')

-    EXPERIMENT_LOCATION = '/experiments'
-    PREVIEW_EXPERIMENT_LOCATION = '/preview_experiments'
+    EXPERIMENT_LOCATION = 'experiments'
+    PREVIEW_EXPERIMENT_LOCATION = 'preview_experiments'

     GS_BUCKET_NAME = os.environ.get('GS_BUCKET_NAME', '')
     GS_PROJECT_ID = os.environ.get('GS_PROJECT_ID', '')
```

Git says this commit was done 2018-07-24 16:23:56 -0400, so this is definitely my fault. I'll undo it ASAP.

**Comment by Datamance** [comment]
Great sadness.

As you can see from our [initial attempts at upgrading dependencies](https://github.com/lookit/lookit-api/commit/24e16fcf3c041b964a5bd59ae20ff32651863bb7#diff-5066d15d40205d7ea67ab948093cddf3L27), django-storages 1.7.1 was initially pinned to a commit sha from april of last year.

You can see [here](https://github.com/jschneier/django-storages/blob/master/storages/backends/gcloud.py#L110) that the current version executes a location check that raises an `ImproperlyConfigured` error upon initialization if there's a prepended slash in the path.

And [here](https://github.com/jschneier/django-storages/blob/d96107d809ec685193e96c0ff278d6e725c2f51f/storages/backends/gcloud.py),  we see the version of that same file at the old pinned commit sha - no `check_location` function to speak of.

We also have an interesting `LocationPrefixedPublicGoogleCloudStorage` mixin/class in our project/storages module with the following comment in the overridden `url` hook of the `GoogleCloudStorage` class:

```
"""
        The parent implementation calls GoogleCloudStorage on every request
        once for oauth and again to get the file. Since we're proxying requests
        through nginx's proxy_pass to GoogleCloudStorage we don't need their url
        nonsense or to use the actual domain or bucket name.
        """
```

[nginx's](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) proxy pass just looks like it does what it says, and we can see exactly how this interact's with OSF's helm charts [here](https://github.com/CenterForOpenScience/helm-charts/blob/a8a13ce8278c1b9fd8a12813af49aaf8162734a3/lookit/templates/configmap.yaml#L84):

```
          {{- if .Values.configEnvs.MEDIA_URL }}
          location /media/ {
              proxy_redirect off;
              proxy_buffering off;
              proxy_pass {{ .Values.configEnvs.MEDIA_URL }};
          }
          {{- else }}
          # location /media/ {
          #     alias /media/;
          # }
          {{- end }}
          location /favicon.ico {
              rewrite ^/(.*)$ /static/$1;
          }
          {{- if .Values.configEnvs.STATIC_URL }}
          location /static/ {
              proxy_redirect off;
              proxy_buffering off;
              proxy_pass {{ .Values.configEnvs.STATIC_URL }};
          }
```

So basically, I accidentally undid a hack, at which point I encountered those same errors from the comment above and just "fixed" the error without really understanding the context of what I had changed.

This still fails to explain two things:

1) why the image field of the study saves with `study_images/` prepended in staging and apparently not in prod (from what I understand - I can't actually see, I just vaguely remember @kimberscott saying something to that effect) seeing as both versions have the same image field definition in their models -

`image = models.ImageField(null=True, upload_to='study_images/')`

2) Why both the static and media files can be found at their respective "single" and "doubled" paths, e.g.:

https://staging-lookit.cos.io/static/static/ace_overlay/ace/ace.js
https://staging-lookit.cos.io/static/ace_overlay/ace/ace.js

I'm sure it has everything to do with the behavior of proxy pass, but it's still confusing to me and I'm tired at this point in the night.

All that said, I am fairly certain that this is at the root of our path peculiarities. Although there is nothing really experience-breaking about this bug, it is somewhat annoying and will inevitably cause missing study icons when deployed to prod due to mismatched paths.

On Monday, I will try to modify the Environment Variables (`STATIC_URL` and `MEDIA_URL`) to see if we can change things to match what the up-to-date dependencies expect. If that still breaks staging, I'll have to resort to the old pinned dependency. Eventually, we should just drop the dependency altogether and author our own storage with smarter handling around these things and other niceties like threaded file uploads.

**Comment by Datamance** [comment]
Closing this out for now seeing as it's "fixed" with the downgrade, but future directions will be to re-upgrade django-storages and to do a new class override to give us the desired behavior
