### ISSUE TITLE
Preview & study participation views returning 500

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#215]
Dependency builds appear to be working (per study logs & GC logs) but the preview view and actual study participation views (not study detail view) return 500 errors (e.g., Rico test: https://staging-lookit.cos.io/exp/studies/8fa4d586-10e1-4589-9778-ac6000bc02ff/preview/)

Sentry reports errors at both https://staging-lookit.cos.io/exp/studies/[STUDYID]/preview/ and 
https://staging-lookit.cos.io/studies/[STUDYID]/[CHILDID]/:

TypeError: _new_pool() got an unexpected keyword argument 'request_context'
in exp/views/study.py in dispatch at line 805 (preview)
in web/views.py in dispatch at line 386 (participate)

I think this is related to setting the versions of requests & urllib3 in requirements/defaults.txt, here (possibly combined w/ the new dispatch calls): https://github.com/lookit/lookit-api/commit/1c6399c9b3fe560e323c2c3d4e71c6f6b19c9830

See related issues people describe w/ changes to urllib3, e.g.: https://stackoverflow.com/questions/45521584/django-1-8-application-migrated-to-new-server-rises-strange-exception

**Comment by Datamance** [comment]
Fixed along with #209
