### ISSUE TITLE
Major dependency updates to improve dev process

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#223]
- [x] Use pipenv instead of requirements.txt
- [x] Use django-storages but not via pinned dependency, to get on stable release
- [x] Update Django
- [x] Update djangorestframework, djangorestframework-jsonapi
- [x] Update django-revproxy
- [x] Update django-storages and google-cloud (will affect experiments)
- [x] Update Docker and Docker python client
- [x] Refactor build process

needed-by #134

**Comment by Datamance** [comment]
- [ x ] Introduce pipenv
- [  ] deprecate requirements.txt
- [  ] document

**Comment by Datamance** [comment]
- [ ] update django storages to 1.7.1 instead of pinned dependency
- [ ] update psycopg to 2.7.5 or even 2.8 if possible

Long story short these are needed to enable ubuntu development and un-screw our dependency management

**Comment by Datamance** [comment]
Testing the above tomorrow morning.

**Comment by Datamance** [comment]
Edit: deferring the query refactors to another ticket.

**Comment by Datamance** [comment]
Edit: will be maintaining requirements.txt alongside pipenv until we've got control of the jenkins piece of the CI pipeline, pending conversations with COS.
