### ISSUE TITLE
When triggering both build and preview, preview status isn't updated

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#247]
**Description**
When building both dependencies and preview dependencies for a study, emails are sent to the researcher indicating success of both processes (and the direct link to the preview works), but whichever process finishes second flips the status of the first one back to 

**How to reproduce**
Create/find a study. Trigger build and then preview build in short succession. Wait for both processes to complete. Check the study detail page during and after. After build is completed, build is shown as done and preview as not done (correctly). After preview is completed, preview is shown as done and build as not done. 

**Expected behavior**
The build/preview statuses should be independently updated upon completion.

**Screenshots**
N/A

** Environment (OS, browser, branch, etc.):**
As of c491a1b, tested on lookit-staging.

**Additional context**
Might also be switching the approved/created/etc. study status back to what it was when build was triggered.

**Comment by Datamance** [comment]
Do we consider this fixed?

**Comment by kimberscott** [comment]
Yep!
