### ISSUE TITLE
Consent videos time out after a minute, then look as if there's a problem with the video

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#262]
**Description**
When using the consent manager on the experimenter interface, after a minute the consent video links time out and the video appears as if there was a problem with recording. So you can effectively only use the consent manager for a minute at a time between reloading.

**How to reproduce**
Go to the consent manager for a study with some responses. Play a consent video ('A'). Wait a minute. Select a different consent video, then 'A' again. You should see a black video and 'Uh oh, we can't load the video.'

**Expected behavior**
The video should either play (by fetching a new link if needed) or say the link has timed out, with an option to refresh/reload. 

**Screenshots**
![Screen Shot 2019-04-01 at 4 57 34 PM](https://user-images.githubusercontent.com/9554627/55359266-6e629b00-549f-11e9-8e71-4edb7d75f4b9.png)

** Environment (OS, browser, branch, etc.):**
On staging as of b336d662719b8b367910ad99b9a9e9222f086e6a

**Additional context**

**Comment by jchu10** [comment]
Could not reproduce this error on prod or staging - maybe it's fixed since updating the consent manager (issues 427, 380)?

**Comment by kimberscott** [comment]
The timeout period has been bumped up, but the problem is still there - not as problematic since people don't spend tons of time on consent coding at a time.

**Comment by Datamance** [comment]
@jchu10 @kimberscott we could just change the error message to add something like "If this video stopped working suddenly, the link may have expired. Try reloading the page"

**Comment by kimberscott** [comment]
That would be perfect! And much simpler than checking for expired links :) I'd leave out the "if," just "This link may have expired. Try reloading the page."
