### ISSUE TITLE
Invoke tasks for local development

### ISSUE THREAD

**Issue by robo360** [lookit/lookit-api#310]
**TL;DR**: Once sentence description of what you want.
Invoke tasks to set up all dependencies to easily get started on contributing to the project
**Narrative**
How will this help developers do their job better?
The invoke tasks will help developers getting started, as all dependencies will be installed and configured automatically. The getting started process that usually takes some days will no longer be an issue. 

**Acceptance Criteria**
This literally just needs Rico sign off.

- [x] Rico sign-off

**Comment by Datamance** [comment]
Moved this to block 5 since it is not critical path.

We can close this out once @Mayowa99 and @robo360 do their presentations at the Boston Python meetup.

**Comment by Datamance** [comment]
Closing this out as the script was technically completed, though we are fixing issues with it now.
