### ISSUE TITLE
Clarify Password Reset Language

### ISSUE THREAD

**Issue by anniecardinaux** [lookit/lookit-api#372]
**Description**
Password reset language is ambiguous for users who might expect standard features in the password reset process, particularly for users who do not yet have an account in the system, but think that they do. 

**How to reproduce**
Send a password reset request to an e-mail not associated with a Lookit account. 

**Expected behavior**
Participants should see on the screen very clear text that tells them that they will not get a reset e-mail if their e-mail address is not yet associated with an account. 

**Screenshots**
Current text reads:
"We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder."

**Environment (OS, browser, branch, etc.):**
Any OS - not specific to browser

**Additional context**
Prior e-mail communication with Kim Scott:
Thanks for checking the language! Sounds like a good thing to address - would you be up for making an issue (or commenting on an existing one if there's something related) here to make sure it gets on the list? 

I did check and we just have the one account under your MIT address, so at least the system's functioning as expected. (If you're not aware of the gmail "+" trick: gmail will treat address@gmail.com the same as address+anythingelseyouputhere@gmail.com, so you can make accounts under addresses like kimber.m.scott+participant1@gmail.com, kimber.m.scott+participant2@gmail.com, etc. in case that's ever useful.)

best,
Kim

On Tue, Oct 22, 2019 at 11:23 AM Annie Cardinaux <anniec@mit.edu> wrote:
Hi Kim,

This is what the text currently says when I reset password:

We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.

I just glossed over the highlighted part the first time, because this process tends to be so standard in most websites, so if there is a way to emphasize that text or make it more clear that they won’t get an e-mail if they haven’t registered yet, I think that would be helpful. 

Best,

Annie

-- 
Annie Cardinaux, M.Ed.
Project Coordinator, Sinha Laboratory
Department of Brain and Cognitive Sciences
Massachusetts Institute of Technology
43 Vassar Street, Building 46-4089
Cambridge, MA 02139
Phone: 617-324-5493
bcs.mit.edu | anniec@mit.edu 

To learn more about our research and sign up to participate, please visit:
http://autismresearch.mit.edu/participate 

From: Kim Scott <kimscott@mit.edu>
Date: Friday, October 18, 2019 at 6:59 PM
To: Annie Cardinaux <anniec@mit.edu>
Subject: Re: Lookit Password Reset Delay?

Ah, ok - you'll actually need to use a *different* email address to create the participant account. I'm actually a little surprised it was possible to create a separate participant account with your same email address - that should have run into some database restrictions. 

You wouldn't necessarily get an alert that that there was no account associated with that email address - for security reasons these systems are generally set up not to disclose that and just to say that the email has been sent (if an account exists). I should check that the language lines up with what's going on though - thanks!

For practical purposes I'd just create a new participant account for testing if there's nothing you need from the possible old one. Or if you let me know which email address you used (or which you might have used) I can see if I can see what's going on from admin.

On Fri, Oct 18, 2019 at 5:00 PM Annie Cardinaux <anniec@mit.edu> wrote:
Hi Kim,

I was able to log into the experimenter portal, but thought I had also created a participant account using the same e-mail (this one), and I didn't get an error message.

I am testing our games via the experimenter portal now, so not an urgent issue, and maybe I am confused about whether I actually did create a separate participant account. Even so, wouldn't I have gotten an alert saying there is no account for that e-mail?

Annie

Annie Cardinaux, M.Ed.
Project Coordinator, Sinha Laboratory
Department of Brain and Cognitive Sciences
Massachusetts Institute of Technology
43 Vassar Street, Building 46-4089
Cambridge, MA 02139
Phone: 617-324-5493
bcs.mit.edu
From: Kim Scott <kimscott@mit.edu>
Sent: Friday, October 18, 2019 4:29 PM
To: Annie Cardinaux
Subject: Re: Lookit Password Reset Delay?
 
Hi Annie,

That's not typical - is this for a participant account you created, or for your experimenter account (authenticating via OSF)? Just checking because the auth system is different for experimenters - you do need to always log in via staging-lookit.cos.io/exp (or lookit.mit.edu/exp on prod) and not via the participant login area. The password reset functions are also separate. If you can let me know the URL you're using (+ screenshot of what you see after making the request) & email address you're checking, I'll take a look for any error logs that would explain the problem.

best,
Kim

---
Kim Scott
Research scientist | Early Childhood Cognition Lab | MIT
W: www.mit.edu/~kimscott | Participate: https://lookit.mit.edu

On Fri, Oct 18, 2019 at 4:11 PM Annie Cardinaux <anniec@mit.edu> wrote:
Hi Kim,

I just requested to reset my Lookit password and have not received an e-mail with a link to do so; it's been about 5 minutes since I sent the initial request. I'm wondering if that's typical. I did check my spam folder and don't have anything from Lookit.

If this is typical, I wonder if it is worth adding some info that tells parents what to expect in terms of password reset wait time to the text that is currently on the website?

Best Regards,

Annie

**Comment by kimberscott** [comment]
Clarified in #526
