### ISSUE TITLE
Clarify demographic form instructions

### ISSUE THREAD

**Issue by LaurieBayet** [lookit/lookit-api#401]
A few simple, low-priority tweaks in the demographic form instructions would limit the chances that someone participating for the first time would encounter an error on the form:
- For child DOB, maybe specify right away that dates should be separated with commas (not just in the error text)
- For number of children's books, maybe specify "enter numerical entries only" (not just in the error text). For example if someone enters "100?" they get an error because it wants only numerical values.

**Comment by kimberscott** [comment]
Thank you so much for catching these! Definitely makes sense to fix & will get on this soon.

**Comment by kimberscott** [comment]
The demographic form could definitely use a more thorough review at some point - e.g., to make the questions about "how many children" clearer (stepchildren who live with you? children who were adopted but you were the birth parent? children who have died?), to make the gender question more inclusive, to what better options we have for recording race/ethnicity, etc. Anyone interested in taking that on please make a new issue about it to organize! For now, just added help-text about children's books (child DOB as comma-separated list is also in the help-text, not just error text).
