### ISSUE TITLE
Error saving JSON script when editing a study

### ISSUE THREAD

**Issue by dunodu** [lookit/lookit-api#407]
**Description**
When editing a study's JSON, the "Save Changes" button is only clickable if the page has recently been refreshed. If the page was not recently refreshed, the edits to the JSON cannot be saved. After refreshing the page, the "Save Changes" button becomes clickable, but the new changes to script get erased (since they were never saved).

**How to reproduce**
Make changes to the JSON script after the browser has been up for a while without refreshing the page.
 
**Expected behavior**
An non-clickable "Save Changes" button

**Screenshots**
![Screen Shot 2020-01-21 at 4 13 50 PM](https://user-images.githubusercontent.com/60162133/72854386-13d23f80-3c69-11ea-9a32-f181ba9509f1.png)

**Comment by kimberscott** [comment]
@dunodu thank you so much for reporting this! I've run into it sporadically too and have been meaning to fix it, but I've never been able to get it to happen reliably enough to dig into it!

I'm still having trouble replicating the non-clickable "Save Changes" button by leaving either the JSON editing window or the study detail view open for a while. Can you confirm some information about when you see this happen?
- How long do you have to wait before this occurs?
- Does it happen regardless of whether you've made any changes to JSON data and/or other study details, and regardless of whether you've previously pressed Save Changes?
- What browser are you using?
- What study (just in case there's something specific to what's being saved)?

**Comment by kimberscott** [comment]
I think this is incidentally fixed by https://github.com/lookit/lookit-api/pull/439 - please comment here if you see it happen again, otherwise I'll close out this issue in a few weeks.
