### ISSUE TITLE
Consent manager view loads slowly, uses a lot of memory for large responses

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#427]
The consent manager view (first thing shown upon clicking "view responses") is generally slow to load (10+ s) and runs out of memory in some cases when response objects are large (e.g., PAIRS on staging). 

We should speed it up for general usability. We could sacrifice loading and showing the exp_data here for accepted responses, which should be very rarely used, and for the response properties (e.g. withdrawn) we can bite the bullet and write separate functions that compute these instead of using the response objects directly.

**Comment by Datamance** [comment]
Should we close this out?

**Comment by kimberscott** [comment]
Yep! Hooray :)
