### ISSUE TITLE
Messaging view OS write errors for Flurps & Zazzes

### ISSUE THREAD

**Issue by Datamance** [lookit/lookit-api#428]
**Description**
For Flurps and Zazzes, we're unable to load the participant messaging view (getting a 502 from nginx), and seeing a corresponding error in the uwsgi logs:

`uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 331] during GET /exp/studies/10/contact/ (10.44.0.1)`

**How to reproduce**
Visit https://lookit.mit.edu/exp/studies/10/contact/

**Expected behavior**
Page loads with 200

**Additional context**
Generally we see these kinds of errors when the process takes too long to finish. The most likely timeline of events is:

1) NGINX starts a request to uWSGI
2) uWSGI takes too long to respond
3) NGINX closes the connection to uWSGI
4) uWSGI finishes the request, tries to give it's response back to NGINX, even though NGINX closed the connection earlier
5) uWSGI throws an I/O error because of the "broken pipe"

This is distinct from an OOM death, which we see when the process is taking up too much memory. 

We also see messages that are on average 3-4x as large as those found in the physics study, as seen here:
![image](https://user-images.githubusercontent.com/8699411/74178369-7637b380-4c09-11ea-9014-96c36b3011ed.png)

**Comment by Datamance** [comment]
OK, after profiling I'm seeing the source of the slowness and it appears to be a regression caused by the generation of the study salt:

![image](https://user-images.githubusercontent.com/8699411/74178996-8d2ad580-4c0a-11ea-9816-1a73f325c61b.png)

![image](https://user-images.githubusercontent.com/8699411/74179081-b5b2cf80-4c0a-11ea-9f2c-fa6b8f58363e.png)

![image](https://user-images.githubusercontent.com/8699411/74179183-f14d9980-4c0a-11ea-834d-2712deef546e.png)

Will confer with Kim on how to go about remedying this problem.

**Comment by Datamance** [comment]
The previous_messages QS is also causing problems:

![image](https://user-images.githubusercontent.com/8699411/74179545-abdd9c00-4c0b-11ea-878b-b82f40645a0d.png)

![image](https://user-images.githubusercontent.com/8699411/74179608-cc0d5b00-4c0b-11ea-9435-53d6f4054518.png)

But not as much as the study one happening inside `participant_hash`: 
![image](https://user-images.githubusercontent.com/8699411/74179648-e7786600-4c0b-11ea-9f61-fa4a702f2b48.png)

**Comment by Datamance** [comment]
@kimberscott we fixed this, right?

**Comment by kimberscott** [comment]
Yes!
