### ISSUE TITLE
Out of the age range warning not displaying

### ISSUE THREAD

**Issue by agboch** [lookit/lookit-api#487]
The warning about the child being out of the age eange for a particular study is not displaying when choosing a child to participate on the study page. It used to display like in the attached image, now no warning message is appearing (for any of the studies on lookit)
![image (3)](https://user-images.githubusercontent.com/48962315/78905849-94c0fc00-7a4c-11ea-83fb-7c1afa7c7456.png)

**Comment by Datamance** [comment]
Hi @agboch - when did you start noticing this?

**Comment by agboch** [comment]
We noticed that yesterday when we activated our new study and wanted to test out if our age ranges are correctly defined - then we checked out other study that has been running for a while now and noticed the problem there too (and in the other Lookit studies).

**Comment by agboch** [comment]
Hi, the warning about the child being out of the age range is still not displaying and we are unfortunately getting some participants out of the defined age range - possibly because they are not getting this warning. Is it possible to fix it anytime soon?

**Comment by kimberscott** [comment]
@agboch Yep! Next time we push code to production the fix currently on staging will be included. See https://github.com/lookit/lookit-api/pull/488 It will indeed be "sometime soon" ;) but you're welcome to temporarily pause your study to avoid this problem!

**Comment by agboch** [comment]
@kimberscott, thank you for the update! We unfortunately cannot afford pausing a study for so long - it's been now 12 days since we noticed this issue and we would loose lots of data if we wouldn't be actively collecting it in the meantime. But we now got another participant out of the age range and we are worried that without the warning they do not realize that they won't get the gift cards for their participation. Any updates on when the fix will be pushed? Thanks!

**Comment by kimberscott** [comment]
We're actually working on a deployment to production (including this fix) today, but may need to work out some issues with that process first.

However, if you can't afford to pause a study for a week or two, beta testing probably isn't a good fit for your lab right now. This is the flip side of using Lookit before everyone else. We're happy either way if you'd like to wait until launch!

**Comment by kimberscott** [comment]
Fixed in https://github.com/lookit/lookit-api/pull/490 after some slight excitement with the deployment (this is why we don't deploy to prod at the end of the week :) ) - will close in a few days if everything's working as expected
