### ISSUE TITLE
Demographic snapshot won't download

### ISSUE THREAD

**Issue by lisachalik** [lookit/lookit-api#498]
**Description**
I've tried to download the demographic data for Flurps and Zazzes in both JSON and CSV format - each one gives back a Server Error (500) message.

**How to reproduce**
On the Demographic Snapshots page (https://lookit.mit.edu/exp/studies/10/responses/demographics/), click the buttons (JSON or CSV) to download the data.

**Expected behavior**
A file should download automatically.

** Environment (OS, browser, branch, etc.):**
Mac OS 10.14.6 (Mojave), on Chrome

**Comment by kimberscott** [comment]
Fix in the works (https://github.com/lookit/lookit-api/pull/500) but it may be a little while before it gets to production since it'll need to be folded in with some larger changes in the works. Thanks for reporting & sorry about that!
