### ISSUE TITLE
Occasional failed experiment runner builds during `get_container_directories` phase

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#504]
**Description**

Sometimes experiment runner builds are failing. The researcher gets an email indicating that the build failed during the `get_container_directories` phase. 

**How to reproduce**

STILL WORKING ON THIS - this is a placeholder to keep track of some issues that have happened sporadically.

1. Clone any study.
2. Set the experiment runner version (commit SHA) to  one of
  * `bd3cdf6aa7ed6eac01fa1c7396428f5548f670d4` - last working version
  * `bd13a209640917993247f7b6d50ce8bd7d846c82` - first breaking version.
  * `1e5e545af32cf10c8461650879b45866ad89d873` - most recent version of feature branch, has worked on prod
3. Build the experiment runner
4. Wait for notification that build succeeded or failed. Note that success (for non-working versions) often (but not always) takes ~50s rather than ~250s. Failure occurs at stage 5: get_container_directories. I haven't yet figured out under what circumstances we get too-fast success, regular-speed fake success, or failure, I'm sorry (i.e. have seen all three for the same SHAs, although not genuine success for any of the 
5. If build succeeded - try to preview the study. For non-working versions, observe the following if this is the first build for this study:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
</Details>
</Error>
```

If it is NOT the first build for this study, previewing will seem to work but will still be using the last successful build. (Note that there are changes to exp-video-config that make it a 3-step process in that last build, so any study starting with that makes it obvious whether the new code is being used.)

**Expected behavior**

The build should succeed and take about 250s, and the updated code version should be used in the study preview. 

**Environment (OS, browser, branch, etc.):**
Staging and production. Changes made between
  * `bd3cdf6aa7ed6eac01fa1c7396428f5548f670d4`
  * `bd13a209640917993247f7b6d50ce8bd7d846c82`
sometimes lead to successful builds in the first case and failed builds in the second.

**Additional context**

This is presumably as much an issue with ember-lookit-frameplayer as with lookit-api, but I'm not sure where the *fix* will end up living, and need some help to figure out what's actually happening here (e.g., what's going on when the ember build process looks like it completes successfully, but it's too fast, and hasn't actually worked). 

One of the changes introduced recently is the addition of video examples in the documentation in ember-lookit-frameplayer. This may be a problem given that we fetch the whole repo - this is my suspicion about failures at the get_container_directories stage. But note that it's not an all-or-nothing problem (the most recent working version does contain a fair amount of video documentation) and that removing the docs/video entirely doesn't fix the problem.

**If you experience this**

Please comment below, noting:
* Your study UUID
* The version of the experiment runner (on your study edit page, there should be a field that says "Experiment runner version (commit SHA)" - copy and paste that)
* The error message you got
* Whether/how this resolved (e.g., you tried again later and it worked)

**Comment by ncuneo0711** [comment]
Your study UUID: 7b9448d2-e122-4329-8048-b7c6d087bcc9

The version of the experiment runner (on your study edit page, there should be a field that says "Experiment runner version (commit SHA)" - copy and paste that): "1e5e545af32cf10c8461650879b45866ad89d873" *This is the one that I used that worked!

The error message you got:
It failed during the get_container_directories stage. Logs are provided below to help with troubleshooting.

Log output:
    [
    {
        "stage": "get_study",
        "success": true,
        "logs": "No logs given."
    },
    {
        "stage": "get_researcher",
        "success": true,
        "logs": "No logs given."
    },
    {
        "stage": "get_player_sha",
        "success": true,
        "logs": "No logs given."
    },
    {
        "stage": "build_docker_image",
        "success": true,
        "logs": "No logs given."
    },
    {
        "stage": "get_container_directories",
        "success": false,
        "logs": "Uncaught failure of type <class 'IndexError'>:\nlist index out of range"
    }
]
I received this error message 15-20 times each time I tried to re-run it!

Whether/how this resolved (e.g., you tried again later and it worked): 
-I tried to make a new version (a few times) with no luck
-Then I added the code above- with immediate success!

**Comment by kimberscott** [comment]
@ncuneo0711 was the experiment runner field initially blank when this wasn't working? If so, I think this is a case of https://github.com/lookit/lookit-api/issues/506 which is now fixed.

**Comment by ncuneo0711** [comment]
@kimberscott - yes! Sorry about that. The field was initially blank when this wasn't working. I was following the tutorial. I didn't check for other (newer) changes. Thanks for letting me know! Sorry again!!

**Comment by kimberscott** [comment]
@ncuneo0711 Nothing to apologize for! This was a perfect place to report the bug and super helpful information, we just had a few related issues going on :)
