### ISSUE TITLE
Experiment runner not building when version is blank

### ISSUE THREAD

**Issue by lisachalik** [lookit/lookit-api#506]
**Description**
When I go to build the experiment runner and I leave the commit sha field blank (so that it will default to the latest version), the build doesn't work, and I get four separate but identical emails saying that it didn't work (screenshot attached).
<img width="578" alt="Screen Shot 2020-06-02 at 5 54 01 PM" src="https://user-images.githubusercontent.com/64935408/83573819-2bb0ae80-a4fa-11ea-9299-96bcf68a2847.png">

**How to reproduce**
Try building an experiment runner with the commit sha field blank.

**Expected behavior**
I should get an email saying the experiment runner is built.

** Environment (OS, browser, branch, etc.):**
Using Chrome on a MacBook running OS Catalina.

**Additional context**

**Comment by kimberscott** [comment]
Eep, that's no good, thanks for catching! I can reproduce that here so we should be all set on info about this bug.

**Comment by kimberscott** [comment]
Should be fixed on staging, turned out to be an environment variable pointing to a defunct default branch!

**Comment by kimberscott** [comment]
Potential regression here? Will dig into this again when there's another report.
