### ISSUE TITLE
Option to download a single participant's videos?

### ISSUE THREAD

**Issue by RaechelDrew** [lookit/lookit-api#507]
Could a feature  that would allow a single participant's videos to be downloaded all at once be implemented?

As an Experimenter, I would love to be able to download all videos for a single participant as a batch, without having to download each video individually. It would make it faster to download and organize all participant data into folders on our own server for research assistants to code at a later date.

Perhaps a button similar to "download all" would suffice, but for only one participant's videos rather than all study videos. 

Thank you!

**Comment by kimberscott** [comment]
This sounds like a good idea. (We've actually been toying with this idea for some time but were waiting to see how it was actually used! 
https://github.com/lookit/lookit-api/issues/162) 

Do you have preferences on...

- downloading videos per participant vs. per session (for longitudinal studies where participants do the "same" study repeatedly - I realize that's not your use case)

- being able to download individual session/participant video collections vs. check off a bunch that you want to download

- how the bulk video downloads are organized (it's a zip file, it doesn't actually have to be a big flat directory - we could have what's in there organized as <child_hashed_id>/<session_uuid>/<video>, for instance. We do this at MIT with some postprocessing for the baby physics study (where we have ~20 videos/session and ~12 sessions/child) but if it's what people want to do in general we might as well set up so you're not all writing your own python scripts to organize videos!

- what this interface looks like / where it lives (e.g., do you just want a "download all from this session" button on "individual responses," or if you want to be able to check off sessions 1, 2, 5, 8, etc. can you sketch out what the interface would look like)

**Comment by RaechelDrew** [comment]
For sure, happy to help! After talking it through with our lab group, we think using the uuid to identify the videos for downloading would be a good way to go. If there was a search button under the videos tab and then an option to check off videos and download using a "download selected videos" button it would be pretty user friendly. Sketch below. But, I will definitely wait and bring it up with folks on Slack after the launch! Thanks so much Kim!

![lookit sketch](https://user-images.githubusercontent.com/66336710/83797326-5401ef80-a657-11ea-8077-78c729239618.jpg)

**Comment by kimberscott** [comment]
incidentally because it was easy while fixing something else, now when you search for a string like above, "download all" and "download all consent" videos are only for the search results - so e.g. you can get just one session, or get just all the "test-trials" or "10-test-trials" videos. I think it makes sense to keep this open and consider what would be most helpful, but that should help in the meantime!

**Comment by RaechelDrew** [comment]
Thanks so much for this Kim! It's very helpful. 
I hope everything is going well for the launch!
