### ISSUE TITLE
Minor security improvements

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#512]
Apply recommendations for security improvements from LMG.

**Acceptance Criteria**
- [x] Set secure flag on SSL session cookies
- [x] Stronger user password requirements
- [x] Session timeout after 1 day
- [x] Remove cross-domain scripts and host ourselves
- [x] Disable autocomplete on password field _(see note below)_
- [x] ~Disable caching https responses~
- [x] ~Remove unused admin login view~

See also see https://github.com/lookit/lookit-api/issues/511.

**Comment by Datamance** [comment]
### Things to consider

#### Remove cross-domain scripts and host ourselves
TODO

#### Disable autocomplete on password field
Please see [MDN's notes on modern browsers and password managers not respecting the autocomplete attribute](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields). In the interest of not breaking [1.3.5: Identify Input Purpose in WCAG 2.1](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html) while still fulfilling the spirit of LMG's suggestion (which was already low NIST 800-30 risk given the fact that an attacker who can already puppet your machine probably already has your credentials), I've only changed the ParticipantUpdateForm and ParticipantSignupForm to produce password inputs with `autocomplete=new-password` attributes. Unhooking the entire auth URLConf and creating new subclasses for LoginView _and_ AuthenticationForm seems like absurd overkill for a low risk item as such.

#### Disable caching https responses
We'll have to do this on a [per-view basis with view decorators](https://docs.djangoproject.com/en/3.0/topics/cache/#controlling-cache-using-other-headers), which bears a larger discussion regarding which data are sensitive to cache. If we don't allow browsers to cache _any_ content, there will be a real noticeable performance impact. Furthermore, we should consider the fact that CsrfViewMiddleware already sets the `Vary: Cookie` header _and_ the actual CSRF token and "expire" cookie on each request - while the goal with this is to prevent users connected through the same caching server or proxy from sharing a CSRF token, this has the additional effect of hinting to the browser to _never cache the page_.

**Comment by kimberscott** [comment]
Regarding disabling autocomplete on the password field - agreed it's low risk, but would we actually need to create new subclasses for LoginView etc? It looks like this could be done by adding `autocomplete='off'` to the `<form>` tag in web/templates/registration/login.html?

**Comment by Datamance** [comment]
My concern with that is that then the email field would no longer have autocomplete. Then it's just a usability tradeoff - honestly up to you if you want to add that in the big PR

**Comment by Datamance** [comment]
Closing this since we merged #520
