### ISSUE TITLE
unable to message participants

### ISSUE THREAD

**Issue by lisachalik** [lookit/lookit-api#546]
**Description**
I click the 'message participants' button on the study page and it gives back a server error (500) message. I tried it with two different studies and it happened both times.

**How to reproduce**
From the study homepage, click 'message participants.'

**Expected behavior**
The portal to send out emails should open.

**Screenshots**

** Environment (OS, browser, branch, etc.):**
Using Chrome on a Mac

**Additional context**

**Comment by kimberscott** [comment]
Looks like this is related to [this error ](https://sentry.io/share/issue/df3ff897d8eb4326a0b1623aeacc418c/) - contact form is populating some data based on existing messages and uses info about the sender, but the new announcement emails don't have a sender. We should be able to get a fix up tomorrow.

**Comment by Datamance** [comment]
@lisachalik this should be fixed - if it's not, let us know and we'll open the issue back up.
