### ISSUE TITLE
Add tabs for studies that are rejected or paused

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#612]
# TL;DR
When navigating studies on the Experimenter interface, show tabs for "rejected" and "paused" studies as well as "active," "created," etc.

# Narrative
As an admin or study reviewer, I would like to be able to see studies that are currently approved and could be made active, as well as studies that might be resubmitted in the future. As a researcher I would like to be able to see my paused & rejected studies as well as these are "in progress."

# Acceptance Criteria

- [ ] Tabs for rejected and paused studies added to study list view

**Comment by mekline** [comment]
We will add these as part of the current shape; pending a vote on Slack for the new arrangement

**Comment by mekline** [comment]
Update - unanimous response to the straw poll was to keep the "Active" study farthest left, so please use the order shown below, with bars/spacers in the indicated locations to help visually group things:

![Screen Shot 2022-08-30 at 4 22 34 PM](https://user-images.githubusercontent.com/6819829/187535883-b36a0e9f-ba66-4401-befb-2bc40e87d832.png)

**Comment by becky-gilbert** [comment]
One suggestion (feel free to ignore): we could add another bar/spacer between "Deactivated" and the "My Studies" / "All" group.

**Comment by mekline** [comment]
+1!
