### ISSUE TITLE
Add help-text about role of feedback and consent notes

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#615]
# TL;DR
Add help text for feedback and consent notes that makes it clear which of these participants can see. 

# Narrative
As a researcher, I want to give feedback to participants and make notes about consent videos, but am nervous I will mix up which text will be visible to participants and/or have tried to reach participants with text that is not visible to them.

# Acceptance Criteria
A precise description of how/when this issue will be considered closed, e.g.:

- [ ] Help text on consent notes field
- [ ] Help text on feedback field

**Comment by becky-gilbert** [comment]
@mekline can you please review my proposed changes? Once you're happy with the new help text, I'll create the PR. Thanks!


## Consent video notes

Here's the current placeholder text for the consent video notes:

![Screenshot 2023-04-12 at 1 09 57 PM](https://user-images.githubusercontent.com/9041788/231575755-66c139f8-5402-48e5-927c-f66e8409e2d6.png)

Here's a screenshot of my proposed change:

![Screenshot 2023-04-12 at 1 18 16 PM](https://user-images.githubusercontent.com/9041788/231575782-5b71fd32-1510-4aa7-8508-6f378876eb90.png)

And the text, for your editing convenience:

> Leave any internal comments here, e.g. why a ruling was made. These comments can only be seen by researchers, and are saved when rulings are submitted.


## Response feedback

Here's the current form for entering feedback about a participant's response (no help text):

![Screenshot 2023-04-12 at 1 24 36 PM](https://user-images.githubusercontent.com/9041788/231577994-8c8fad51-3110-4df5-8606-09a7fae64490.png)

Here's my proposed change (placeholder help text in the feedback box):

![Screenshot 2023-04-12 at 1 29 54 PM](https://user-images.githubusercontent.com/9041788/231578027-98cbf0bd-88b7-4739-9c55-6d7dcd8c7c76.png)

And the text, for your editing convenience:

> Add any feedback for the family/child here. This feedback will appear alongside the other session information in the family's study history.
