### ISSUE TITLE
Add opt-out info to study_announcement email templates

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#673]
# TL;DR
Add the same "update your email preferences" link in the study announcement emails as in custom emails

# Narrative
As a participant, I need to know how to opt out of future study invitations.

# Acceptance Criteria

- [ ] Update your email preferences link added to study_announcement.html, study_announcement.txt
- [ ] Tests updated to pass if needed

**Comment by becky-gilbert** [comment]
Closing this issue as completed, becasue the 'update your email preferences' link was added to the study announcement emails in this commit: https://github.com/lookit/lookit-api/commit/13812a282504ff8f0cdd07c1dddc446d46e62380.
