### ISSUE TITLE
Link to researcher registration form is unclear

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#703]
Reconsider how to direct researchers and participants to create the appropriate type of account. Considerations include making it unlikely for participants to accidentally sign up as researchers (less of a problem if researchers sign up as participants). 

It is not clear that the link, this form, on the sign up form is a link. There is not sufficient difference in color from the surrounding text and the color difference with the background does not meet the contrast minimum for regular text. Also, the link label of "this form" is not clear - change to "researcher registration form." See https://github.mit.edu/Accessibility-FY2021/lookit/issues/15

![image](https://user-images.githubusercontent.com/9554627/119868031-86ea6680-beec-11eb-80be-b49816c40e93.png)

Update 2/23: Use .alert-link if available in v3, otherwise please modify the link to match.  New text for the alert box:

"Ready to participate in a Lookit study? Create a family account here! (To register as a researcher, please use the **[researcher registration form](https://lookit.mit.edu/registration/)** instead.)"

**Comment by mekline** [comment]
@okaycj This issue is ready to go for the current sprint, see above!
