### ISSUE TITLE
Remove tab and tablist roles for nav bar

### ISSUE THREAD

**Issue by kimberscott** [lookit/lookit-api#721]
See https://github.mit.edu/Accessibility-FY2021/lookit/issues/5: 

>     * remove tab and tablist roles
> 
> 
> ```
> 
> <div class="panel-group" id="accordion" role="tablist">
> ...
> 
> <div class="panel-heading" role="tab">
>         						<h4 class="panel-title">
> <a data-toggle="collapse" data-parent="#accordion" href="#collapse0" class="collapsed" aria-expanded="false">Who can create studies on Lookit?</a>
> </h4></div>
> ...
> </div>
> ```

**Comment by mekline** [comment]
@okaycj please update with more context, mekline can't see that repo right now
