### ISSUE TITLE
FAQ dead links

### ISSUE THREAD

**Issue by okaycj** [lookit/lookit-api#744]
**Description**
There are two links within the same section on FAQ page that are dead.  

**How to reproduce**
1. Goto https://lookit.mit.edu/faq/
2. Click "Who will see our video?"
3. "mission" and "requirements for authorized users" return a 404. 

**Expected behavior**
Both "mission" and "requirements for authorized users" would go their appropriate page.  If the case is there is no replacement page, then the FAQ copy should reflect this reality.  

**Screenshots**
<img width="715" alt="Screen Shot 2021-07-12 at 10 53 45 AM" src="https://user-images.githubusercontent.com/44074998/125332787-744eb400-e317-11eb-9952-d0826495251f.png">

** Environment (OS, browser, branch, etc.):**
All and any. 

**Additional context**
Currently, I am unsure what the correct page should be for either of these links.

**Comment by kimberscott** [comment]
Fixed in https://github.com/lookit/research-resources/commit/580f21caa16c8f8dc380e288007706e13e65d02a (+ manual update of prod db from Admin)
