### ISSUE TITLE
Create fake data on staging for front end QA

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#787]
For QA of the front end views on staging, please make the following studies, using distinctive names/pictures as you see fit :). Use whatever labs/permissions that would let me view all study info & participant/response data, and maybe even edit the studies if that's possible

1) A scheduled external study, including the link to calendly.com homepage, that is available to 1-2 year olds.

2) A sync/unscheduled external study, including a link to qualtrics.com homepage, that is available to 1-6 year olds.

Please then create 5 records for each study. It would be great if some of these were duplicate participants and some were from a variety of different fake families, but don't worry about the latter if you're not set up to do that easily!

**Comment by okaycj** [comment]
@mekline 

> It would be great if some of these were duplicate participants

Currently, we'll allow a user to participate in a study multiple times, but we only record the first one.  There's no update to the response record if they've already clicked the study link.

**Comment by okaycj** [comment]
@mekline I have created the above studies, users, children, and responses.  This is ready to be reviewed.  Let me know if further work is necessary.

**Comment by okaycj** [comment]
The fake studies have been created.  Closing issue.
