### ISSUE TITLE
Exit URL not displaying on researcher study view

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#836]
**Description**
In the researcher's detail view of a study, the value of Exit URL is appearing as "None Specified" for all studies. This is important in case it indicates more far-reaching trouble with the new pattern for specifying these.

**Expected behavior**
The Exit URL should list whatever the researcher provided for studies prior to latest update; for studies since the update, the default URL we selected should appear (though in the long term we may want to retire this field!)

**Screenshots**
<img width="508" alt="Screen Shot 2021-10-16 at 1 00 30 PM" src="https://user-images.githubusercontent.com/6819829/137767926-bdce61e0-626d-43e5-8ba3-3c740669bf53.png">

**Additional context**
Mark S. reported this and would have more details about context if needed

**Comment by okaycj** [comment]
@mekline This appears to be working.  Could you confirm this for me?

**Comment by mekline** [comment]
Yes, it seems to be working as intended!
