### ISSUE TITLE
Can't click through 'individual responses' pages

### ISSUE THREAD

**Issue by lisachalik** [lookit/lookit-api#856]
**Description**
On the Individual Responses page for a study, there is no way to click past the first page of responses.

**How to reproduce**
1. Open the Individual Responses page for any study.
2. Scroll down to underneath the box that lists all of the responses.
3. It says "Page 1 of n" but there is no way to get to page 2.

**Expected behavior**
Previously, there was a Next button next to "Page 1 of n" to allow users to click to the next page.

**Screenshots**
![Screen Shot 2021-11-02 at 4 11 00 PM](https://user-images.githubusercontent.com/64935408/140384517-0595fea7-ae62-43ac-8479-8042824047d1.png)

** Environment (OS, browser, branch, etc.):**
Mac OS 12.0.1, problem occurs in Chrome and Safari

**Comment by okaycj** [comment]
@lisachalik This appears to have been resolved by #851 and deployed to production with #855.  Could you confirm the bug is resolved?

**Comment by lisachalik** [comment]
Confirmed!
