### ISSUE TITLE
New External studies take researchers to old 'edit study' page

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#860]
**Description**
Report from Natalie B.:

Hi Melissa! I saw your message about the correct way to make an external study - it should have the 4 check boxes at the top (rather than 2). I went back and made a new study (which included the 4 check boxes), but now that I go back in to edit the new study, only 2 check boxes appear. Is there a way to make sure my new study is the correct form? Thanks!

To clarify: I did NOT clone the study. I made a new study and copied and pasted over all the information from the old study.

**How to reproduce**

(1) Two versions of the study exist 

Original: https://lookit.mit.edu/exp/studies/1324/
Re-created: https://lookit.mit.edu/exp/studies/1277/

Natalie re-created the study from scratch following my instructions. Clicking "Edit study" on either will take you to the old, two-checkbox version of the edit-study form.

(2) Clicking "clone study" on an existing study also takes you to the old version of the form.

**Expected behavior**
All studies (including ones created prior to the ExStudies change) should go to the new edit form (4 checkboxes on top) when clicking edit study.

**Comment by okaycj** [comment]
@mekline The 4 vs 2 check boxes is the expected behavior from what I remember.  On the creation form, you can select external/scheduled.  On the edit for, you are not allowed to change the study type.  When you clone a study, the study is automatically saved and you're presented with an edit form.  

What is the expected behavior from your point of view?  Could this be a feature request?

**Comment by mekline** [comment]
Ah! Okay, that makes sense. And the same behavior for the clone study option makes sense too. I'm going to review the requests from researchers on this topic, but suspect this will become a small feature request. Better for me to update this one, or make a new issue if that turns out to be the case?

**Comment by okaycj** [comment]
Whichever is easier.  I have no problems with this turning into a feature.

**Comment by mekline** [comment]
Melissa is wrong about the implementation of the new Edit page! This is turning into feature request #861, closing this bug report.
