### ISSUE TITLE
Giving parents a clear way to opt-out of emails

### ISSUE THREAD

**Issue by lisachalik** [lookit/lookit-api#864]
# TL;DR
Notification emails could include a link to update notification preferences.

# Narrative
A number of parents have responded to new study notification emails, saying that they want to be "unsubscribed." It would be nice (for both researchers and parents) to pre-empt this by adding a link at the bottom of these emails saying something like, "click here to update your notification preferences."

# Acceptance Criteria
The issue will be closed when parents have an easy way to find out how to update their preferences.

**Comment by mekline** [comment]
Closing, realized this is a duplicate of #673; adding @lisachalik 's notes as a comment there for context
