### ISSUE TITLE
Provide list of CHS lab website links

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#910]

**Comment by msheskin** [comment]
The below link (limited to view by CJ/Melissa) has a list of all websites in "Original" tab, and then another couple of tabs to begin cleaning it up. There is still finalization to be done before we have what we would want to post, especially deciding how short to make the slugs (e.g., always to homepage, or do we sometimes point to a specific research page if it seems likely to be the more relevant page for parents and unlikely to change slugs anytime soon). https://docs.google.com/spreadsheets/d/1OCPquafs0QtTZAj6dKpNw60muRWAyw_SlJTMC89VvQ8/edit#gid=1623162551

**Comment by mekline** [comment]
Closed via off-git communication
