### ISSUE TITLE
Evaluate pipe feature set & alternatives

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#911]
# TL;DR
The AddPipe integration creates headaches for some institutions' IT departments - evaluate whether we can remove and replace either with another service or else our own implementation

# Implementation Notes

* Do other equivalent services exist?
* What full feature set do we use? (See especially replay of video & audio back to user during AV setup frame)
* What does the current JS api provide?
* What are browsers currently providing in terms of codecs and file sizes? Do we need compression as a separate step circa 2022?

**Comment by becky-gilbert** [comment]
The [media recorder API](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) will allow us to do the in-browser recording, including things like displaying the live camera feed and playing recorded video/audio back to the user. It's supported by recent versions of modern browsers (not IE): https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder#browser_compatibility

jsPsych recently introduced some video recording tools, and it might help to look at their implementation: [web cam initialization](https://www.jspsych.org/7.3/plugins/initialize-camera/), [mirroring the camera feed](https://www.jspsych.org/7.3/plugins/mirror-camera/), and video recording ([plugin](https://www.jspsych.org/7.3/plugins/html-video-response/) and [extension](https://www.jspsych.org/7.3/extensions/record-video/)).

I think the trickier part is streaming the recording directly to the cloud. (I assume we're streaming to avoid hitting browser memory limits, but maybe that's not always necessary).

A few links that may or may not be helpful:
https://cloud.google.com/storage/docs/streaming#stream_an_upload
https://cloud.google.com/storage/docs/reference/libraries
https://www.woolha.com/tutorials/node-js-upload-file-to-google-cloud-storage
https://www.npmjs.com/package/multer
https://stackoverflow.com/questions/70044591/upload-direct-stream-a-file-from-frontend-to-google-cloud-storage-using-multer

**Comment by mekline** [comment]
Another possible thing to consider - users have the option of either recording/streaming the entire session, or turning the camera on and off for key segments.  Is one of these better under Pipe? Would a different one be better under our own solution? That would be fine; some adjustments to the 'preferred' 
user behavior would be okay but should be considered as part of the tradeoff we make.

**Comment by becky-gilbert** [comment]
Closing this issue as we've decided on RecordRTC for client-side recording and AWS S3 for upload/storage, and we've moved on to implementation (see relevant ember-lookit-frameplayer [issue](https://github.com/lookit/ember-lookit-frameplayer/issues/307) and [branch](https://github.com/lookit/ember-lookit-frameplayer/tree/replace-pipe)).
