### ISSUE TITLE
Update color palette CSS - see also #706

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-api#923]
Update primary color scheme to use the CHS color palette, see slide deck for how they are used: 
https://docs.google.com/presentation/d/1s91BnmNT-vR6RqSeadoU2wB1c-wjkNBsJjS_bg_kLSw/edit#slide=id.g114d8449877_0_0

**Comment by becky-gilbert** [comment]
The link in #706 is broken for me, but I think we can use these to check the contrast: 
https://www.tpgi.com/color-contrast-checker/
https://github.com/ThePacielloGroup/CCAe
