### ISSUE TITLE
Merge Log model and Study Log model 

### ISSUE THREAD

**Issue by okaycj** [lookit/lookit-api#995]
# TL;DR
There is only one "Log" table.  Therefore, we can merge the Log model with the Study Log model.  

# Narrative
Before removing Response Log Table, there were two Log models.  Now that there is only one, we can remove the subclass model "Log" by merging the fields and classes.  This should fairly easy and have no impact on the user or database.   

# Acceptance Criteria
- [ ] There only on "Log" class in the model
- [ ] The are no new migrations
- [ ] Tests pass

Created from #992

**Comment by mekline** [comment]
(Maybe obvious, but for QA, please ensure that study logs & the comment box - both the most recent and the full record - remain as-is on researcher study detail page):

![Screen Shot 2022-07-20 at 10 51 08 AM](https://user-images.githubusercontent.com/6819829/180013026-55d3885c-7428-4945-93aa-c36ae0422875.png)

**Comment by mekline** [comment]
Whoops, I accidentally deleted a comment! Maybe this is obvious, but for QA, can you please ensure that the study logs are continuing to display as they currently do, e.g.: 
![Screen Shot 2022-07-20 at 10 07 53 AM](https://user-images.githubusercontent.com/6819829/180014629-49433d41-25f6-478b-a159-6c279bd53566.png)

**Comment by mekline** [comment]
@okaycj - we'll need to define what appears in this view for new submitted study text.  Should I put that here or open another issue?
