### ISSUE TITLE
Eliminate "who like dinosaurs" from template field text in participant criteria

### ISSUE THREAD

**Issue by msheskin** [lookit/lookit-api#997]
# TL;DR
Eliminate "who like dinosaurs" from template field text in participant criteria

# Narrative
As an admin reviewer, I am likely to ask researchers to take out "cute" inclusion/exclusion criteria that "they do not really mean" but the current Eliminate template field text in participant criteria encourages this ("...who like dinosaurs"). 

# Acceptance Criteria
When that text is deleted :)

**Comment by becky-gilbert** [comment]
Thanks @msheskin, I agree.

@mekline are you ok with this change, and if so, happy for me to take it?
